version: "3"

networks:
  tictactoe:
    driver: bridge

services:
  tictactoe:
    build:
      context: ./
      dockerfile: TicTacToe/Dockerfile
    ports:
      - 5000:5000
    environment:
      SERVICE_PORT: 5000
    networks:
      - tictactoe
